name: Улучшение SDK
description: Предложите идею для проекта
title: "[FEATURE]: "
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        > Пожалуйста, перед заведением баг репорта, поищите похожие проблемы в issues.
        > Сами issues находятся здесь: https://github.com/VKCOM/vkid-android-sdk/issues
        >
        > Аккуратно заполните информацию ниже, чтобы помочь нам разобраться в ситуации

  - type: textarea
    attributes:
      label: Связан ли ваш запрос с какой-то проблемой?
      description: |
        Четкое и ясное описание того, в чем состоит проблема. Например, у меня постоянно возникаю проблемы, когда [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Опишите решение, которое вы предпочитаете
      description: |
        Описание того, чтобы вы хотели получить в итоге
    validations:
      required: true

  - type: textarea
    attributes:
      label: Расскажите об альтернативных решениях, которые вы рассматривали
      description: |
        Описание альтернативных решений, их плюсы и недостатки
    validations:
      required: false

  - type: textarea
    attributes:
      label: Дополнительные заметки
      description: |
        Добавьте любую информацию, которую посчитаете нужной
    validations:
      required: false
