build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true
  excludes: "ui-tests"

ui-tests:
  active: true
  RestrictedKeywordRule:
    active: true
    includes: "**/androidTest/**"
  TestClassNamingRule:
    active: true
    includes: "**/androidTest/**"
  TestMethodNamingRule:
    active: true
    includes: "**/androidTest/**"

complexity:
  active: true
  NestedBlockDepth:
    # increased from 4 to 5
    active: true
    threshold: 5

style:
  active: true
  MaxLineLength:
    # disable to prefer ktlint rule
    active: false

formatting:
  active: true
  MaximumLineLength:
    active: true
    maxLineLength: 150
  ArgumentListWrapping:
    active: true
    maxLineLength: 150
  Wrapping:
    active: true
    maxLineLength: 150
