complexity:
  active: true
  LongParameterList:
    active: true
    ignoreDefaultParameters: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 20

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: ["Preview"]
